spring:
  application:
    name: s3-manager
  cloud:
    aws:
      s3:
        #endpoint: http://s3.localhost.localstack.cloud:4566
        region: us-east-1
      credentials:
        access-key:
        secret-key:
      region:
        static: us-east-1
  jackson:
    serialization:
      fail-on-empty-beans: false #to avoid exception empty object serialization

